### ISSUE TITLE
Project Data Ideas 

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/group29#1]
Please add your ideas for dataset/project question here.

**Comment by rachelywong** [comment]
Here's an interesting dataset I found: https://data.world/informatics-edu/diabetes-prediction

Question: Given a person’s background, demographic, and current health status, can we determine their potential onset of diabetes? 

Type: Predictive

Potential Data Analysis: 
-Machine Learning, predict either diabetes or no diabetes, unsure of which classification method to use yet (maybe RBF SVM?)
-Could add different weights to more important factors (like blood sugar levels)
-Randomizedsearch for hyperparameter optimization

Additional Information:
-Importance: Diabetes prevalence is rising, especially right now with the economy and covid-19, more prevalent around low-middle class income groups
-Can be prevented/delayed easily with early treatment/lifestyle changes

**Comment by sukh2929** [comment]
I found the wine dataset interesting present here -> http://archive.ics.uci.edu/ml/index.php

**Comment by wiwang** [comment]
The data set is almost clean and its size should neither too large nor too small.

**Comment by jraza19** [comment]
StackOverflow 2020 Survey Dataset: https://insights.stackoverflow.com/survey

Question: Do devOps specialists spend more years coding professionally than data scientists? 

Type: Estimation

**Comment by rachelywong** [comment]
Summary from Zoom discussion: Go with Diabetes dataset
