### ISSUE TITLE
Teamwork Contract Done! 

### ISSUE THREAD

**Issue by rachelywong** [UBC-MDS/group29#10]
Please review and comment if you are good with it and I can close this issue if there are no problems!

**Comment by sukh2929** [comment]
we can also add the time availability of individuals in this doc. Also, I think we should add the agenda/mom to GitHub rather than google doc so that everything is in one place.

**Comment by wiwang** [comment]
Let's work together to complete the our first milestone.

**Comment by jraza19** [comment]
Some comments for the contract: 

second bullet in communication - viz should be replaced with via. 
second bullets in expectation  - perhaps a timeframe for when to let the team know by - like let the team know one day beforehand
second bullet in dealing with conflicts - any conflict between team members outside of the unacceptable behavior mentioned in the Code of Conduct file will first be dealt among the entire group.

**Comment by sukh2929** [comment]
I have made the changes as suggested. Please review and then we can close this issue!

**Comment by rachelywong** [comment]
Hi Sukhdeep! I think it looks good, thank you! I think there are just a few nit picky things that could be fixed:

- Dealing with Conflicts bullet 2: I originally had "If there is unresolved conflict, the course instructor or teaching assistants will be called upon as mediators to resolve the conflict." I think we should keep this to specify the course instructor as mediators and instead add another bullet above bullet 2 with Javairia's suggestion "Any conflict between team members outside of the unacceptable behaviour mentioned in the Code of Conduct file will first be dealt with among the entire group."

- Non-availability hours, capitalize K in Kaur

**Comment by sukh2929** [comment]
changes completed!

**Comment by rachelywong** [comment]
Looks good to me! I'm good to close this issue if everyone else is good as well :)

**Comment by wiwang** [comment]
It seems we are in good progress, really feel proud of us

**Comment by sukh2929** [comment]
closing this issue
