### ISSUE TITLE
Milestone 1 - Plan of Action 

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/group29#2]
Adding details on the plan of action and splitting of work tasks for the group.

**Comment by jraza19** [comment]
**Lab 1 - Nov 18 Meeting Minutes:**
Created by Rachel, Edited by Javairia 
Contributions from Everyone

Milestone 1 requirements (Due Sat):
Project set up

- GitHub repo (Javairia)
- File and Directory structure, make repo look nice (Rachel)
- Teamwork Contract (Rachel - editor/Everyone contributed)
- Code of Conduct File (Javairia)
- Contributing File (Zhiyong)
- License File (Sukhdeep)

Project proposal (written in the README of repo root)

- Identify dataset, research question, and plan of action (Rachel proposed/Everyone contributed)
- Type of question (Rachel)
- Detailed plan (Everyone contributed)
- At least one EDA table and at least one EDA figure (Everyone contributed - GH Issue)
- How we would share our results (Everyone contributed)
- Write up README using ideas from GitHub issue Page (Javairia/Sukhdeep)
- Proper grammar, written English (Javairia - Designate Role for Milestone 1)

Script that downloads and saves the data

- Python (Zhiyong/Sukhdeep - Team contributed)
- Use docopt
- Put in proper folder in rep


EDA in .rmd or .ipynb

- What kind of data do we have? Categorical, numerical, etc. (Team contributed)
- Test out different visualizations (Team contributed - GH issue)

Final checklist

- Everyone forks (Team contributed)
- Proper git commit messages (Team contributed)
- GitHub issues (Team contributed)
- Include URL of repo in milestone 1 Canvas submission (Javairia - Designate Role for Milestone 1)
- Create release (0.0.1) and add URL to Canvas submission (Javairia - Designate Role for Milestone 1)
- Submit on Canvas and push to GitHub (Javairia - Designate Role for Milestone 1)

**Comment by rachelywong** [comment]
Just completed the Teamwork Contract and added an issue about it for it to be checked!

**Comment by rachelywong** [comment]
Things to discuss in tomorrow's meeting before submission:

- Review all files (everyone must agree before submitting) and close all issues
- Review src scripts download data properly, and uses docopt
- Final proposal review
- Final EDA review, review data wrangling and that figures make sense, add information learned from figures
- Repo organization, should we delete the data processed folder since we have nothing in it yet?, etc.
- Create 0.0.1 release
- Add URL of repo and URL of version to Canvas submission

**Comment by rachelywong** [comment]
Final tasks as discussed:

@jraza19 
- keep: overlapping histograms, age plot, categorical, race plot, 
- move race up
- sort race list
- add descriptions
- export to html
- submit

@sukh2929 
- drop_duplicates, keep = 'first'
- make a yes or no plot for updated readmission showing we got rid of class imbalance
- send code to Javaria (plots of comparing numerical features vs other numerical features)

all of us
- help with descriptions
- review EDA
- references
