### ISSUE TITLE
Please update the script to reflect the ask 

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/group29#24]
@wiwang just double checked the instructions and we need the script to be able to take a url and file name at the command line. 
Here is what Tiffany has said :
To prove to us that you can get the data into R or Python, write a script that takes a URL and a local file path as command line arguments which downloads and writes the file to your laptop. (edited)

**Comment by wiwang** [comment]
The original design of my code has take this feature into consideration, I verified this feature with test below:
```python
python src/download.py --url https://archive.ics.uci.edu/ml/machine-learning-databases/00480/Measurements_Upload_Smaller.zip --local_path=./
```
