### ISSUE TITLE
Script 2 data cleaning/pre-processing, reads in data from the first script

### ISSUE THREAD

**Issue by sukh2929** [UBC-MDS/group29#31]

**Comment by jraza19** [comment]
@wiwang @rachelywong @sukh2929 please review my PR request for this. To run the script - please do:

`python src/process.py --input="data/raw/dataset_diabetes/diabetic_data.csv" --output="data/processed"`

you might have to download feather - `pip install feather-format`

**Comment by rachelywong** [comment]
Hi @jraza19 just took a look at your script from your branch and it looks good to me. I haven't run it yet to test since we'll need to complete the PR first before the process.py is in our forks. I am good to merge your PR when everyone else is good too :)

**Comment by rachelywong** [comment]
Merged!

**Comment by jraza19** [comment]
Script 2 - issue with data being lost from 100, 000 + rows to 497 after processing. Issue resolved ! The issue was the cleaning code!

**Comment by jraza19** [comment]
closing issue!
