### ISSUE TITLE
Script 3  creates exploratory data visualization(s) and table(s) 

### ISSUE THREAD

**Issue by sukh2929** [UBC-MDS/group29#32]

**Comment by jraza19** [comment]
So i am unable to save to png - but i am seeing that it mgiht a windows issues - were any of you able to save to png? https://www.gitmemory.com/issue/altair-viz/altair/2229/655427611
6:59
I have tried add from suggested colleagues on Slack and no luck

**Comment by jraza19** [comment]
issue might be related to windows. The script works on Zhiyongs system!

**Comment by jraza19** [comment]
NVM issue of pngs resolved by installing additional packages -  `npm install -g vega-lite vega-cli canvas`

**Comment by jraza19** [comment]
Able to run script and produce the plots!
