### ISSUE TITLE
Script 4 - performs some statistical or machine learning analysis 

### ISSUE THREAD

**Issue by sukh2929** [UBC-MDS/group29#33]

**Comment by rachelywong** [comment]
Just completed my section of script 4 and am able to pass it to @sukh2929 now to do her part and then @wiwang can take over when Sukhdeep finishes.

I'm just waiting for the PR from @jraza19 for script 2 to be accepted and then I can pull and request a PR for everyone for script 4.

**Comment by rachelywong** [comment]
@wiwang 

Script 4:
- remove data cleaning and import processed data from script 2
- save results_dict table into png and save it into reports/figures folder for use in script 5

**Comment by wiwang** [comment]
How to save table into png file:
`https://stackoverflow.com/questions/35634238/how-to-save-a-pandas-dataframe-table-as-a-png`

'import matplotlib.pyplot as plt
import pandas as pd
from pandas.table.plotting import table # EDIT: see deprecation warnings below

ax = plt.subplot(111, frame_on=False) # no visible frame
ax.xaxis.set_visible(False)  # hide the x axis
ax.yaxis.set_visible(False)  # hide the y axis

table(ax, df)  # where df is your data frame

plt.savefig('mytable.png')'

**Comment by sukh2929** [comment]
completed my section of the script 4 and @wiwang can take work on this now

**Comment by wiwang** [comment]
now I merged script 4 and its jupyter notebook into main repository, all generated csv files and graphic images are kept under reports/figures folder.
