### ISSUE TITLE
Script 5 - literate code document which presents the analysis and findings

### ISSUE THREAD

**Issue by sukh2929** [UBC-MDS/group29#34]

**Comment by rachelywong** [comment]
Does anybody have any improvements to suggest for our model?

I'm thinking:

1. use larger subset of our data or even the entire dataset (do this by doing what Tiff talked about to Sukhdeep), would be important for getting a more accurate prediction
2. test other classifiers, may get improved scores (accuracy vs. recall, talk about which one is more important to our question cause it's more detrimental to say a patient will not get readmitted when they actually do?)
3. try multi-classification instead to get a more specific prediction (how long patients are readmitted for, can analyze severity of different patients, more informative to improving the healthcare system)

**Comment by sukh2929** [comment]
As suggested by Tiff, we can split data 50:50 as we have a huge dataset for better results and speed. 
Analyze features which are correlated and think through which to keep.
and definitely, we can test with other classifiers

**Comment by jraza19** [comment]
Report reviewed during team meeting - changes reviewed and confirmed!
