### ISSUE TITLE
Project Proposal Ideas 

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/group29#4]
Please add your comments here for what you think should be a part of the project proposal.

**Comment by rachelywong** [comment]
After our zoom discussion:

New question: Based on a patient's demographic and hospital background, can we predict if they will be readmitted to the hospital?

Type: Predictive

Similar to our original diabetes idea in the closed Project Proposal Ideas

Dataset: https://archive.ics.uci.edu/ml/datasets/diabetes+130-us+hospitals+for+years+1999-2008#
Feature description: https://www.hindawi.com/journals/bmri/2014/781670/tab1/

**Comment by rachelywong** [comment]
Note: Closed previous project idea because we thought our dataset was open, but it did not have free access. New dataset has been checked for open access.
