### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by rachelywong** [UBC-MDS/group29#40]
Please post any figures you create and save into the reports/figures folder in the reports folder and post which script you got the figure from.

https://github.com/altair-viz/altair_saver/issues/20

Format for Naming Figures:
figureNUMBER_SMALLDESCRIPTION_scriptNAME.png

ex// figure1_scatterplot_script4.png

**Comment by jraza19** [comment]
for saving altair images - https://github.com/altair-viz/altair_saver/issues/20

**Comment by jraza19** [comment]
All images saved with the appropriate file format.
