### ISSUE TITLE
Proposal and EDA

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/group29#45]
I see that you have done a great job in your proposal and your EDA file. I see no issues at all, keep up the good work!

**Comment by rachelywong** [comment]
@hsmohammed Just wondering, we noticed that we lost marks in some of our written and analysis, and we are unclear about what we should fix from that since you had posted in this issue that there were no issues.

**Comment by hsmohammed** [comment]
I re-reviewed your proposal and EDA and I see that it is fare to give you the full mark on the reasoning section, as you did a very good job in the proposal and the EDA compared to most groups. I changed that grade on Canvas. Just for future submissions, could you explain this sentence:
"Class imbalance here was avoided by changing the readmitted column to binary "YES" or "NO" values if the patient was readmitted or not".

Regarding the writing, it is excellent actually except for some minor unclear sentence structures such as using "This would then give us" and "This will also allow us". It is better to starting sentences by using such references that maybe confusing to the readers. Also, using abbreviations such as RBF SVM is not recommended.

**Comment by jraza19** [comment]
Feedback understood and incorporated.
