### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by rachelywong** [UBC-MDS/group29#61]
1. Create Makefile (driver script to run all other scripts)

- well documented (uses READme and comments to explain what it does)
- `all` target to run all
- `clean` target to undo analysis

2. Project feedback

- create 1 to 2 issues with feedback
- close issues when feedback has been addressed

3. Milestone 2 fixes

4. Submission

**Comment by jraza19** [comment]
processing data
```
#process the data
diabetes_clean.csv : data/raw/dataset_diabetes/diabetic_data.csv
    python src/processingdata.py data/raw/dataset_diabetes/diabetic_data.csv diabetes_with_clean.csv

diabetes_with_race.csv : data/raw/dataset_diabetes/diabetic_data.csv
    python src/processingdata.py data/raw/dataset_diabetes/diabetic_data.csv diabetes_with_clean.csv
```

**Comment by rachelywong** [comment]
project feedback moved to milestone 4

**Comment by sukh2929** [comment]
need to add package - kableextra 1.3.1

**Comment by jraza19** [comment]
Updated the dependencies and the usage section to the make file

**Comment by jraza19** [comment]
> processing data
> 
> ```
> #process the data
> diabetes_clean.csv : data/raw/dataset_diabetes/diabetic_data.csv
>     python src/processingdata.py data/raw/dataset_diabetes/diabetic_data.csv diabetes_with_clean.csv
> 
> diabetes_with_race.csv : data/raw/dataset_diabetes/diabetic_data.csv
>     python src/processingdata.py data/raw/dataset_diabetes/diabetic_data.csv diabetes_with_clean.csv
> ```

ignore - code updated in makefile

**Comment by rachelywong** [comment]
done!
