### ISSUE TITLE
Makefile issues 

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/group29#67]
Please post issues and plan around the makefile script.

**Comment by jraza19** [comment]
Please prepare the paths that are needed to be added beforehand!

**Comment by rachelywong** [comment]
Script 1 - @wiwang 
Script 2 - @jraza19 
Script 3 - @jraza19 
Script 4 - @wiwang and @sukh2929 
Script 5 - @rachelywong 

`all` command
`clean` command

**Comment by rachelywong** [comment]
```
# render report
doc/SCRIPT5.md: doc/SCRIPT5.Rmd doc/references.bib
	Rscript -e "rmarkdown::render('doc/SCRIPT5.Rmd', output_format = 'html_document')"
```
^^ I think this is the right code to render the report? but maybe the .md is not required and we just need .Rmd and references.bib (may not need line 2)

**Comment by rachelywong** [comment]
```
# Makefile
# Group29: Zhiyong Wang, Javairia Raza, Sukhdeep Kaur, and Rachel Wong
# Date: December, 2020

# This driver script completes the exploratory data analysis,
# data cleaning and wrangling, and machine learning analysis 
# of diabetic patient encounter data. Figures of machine learning 
# model analysis and features most predictive of patient readmission 
# are generated in a rendered .html report. This script takes no arguments.

# example usage:
# make all
```

**Comment by sukh2929** [comment]
we all working simultaneously on the makefile

**Comment by rachelywong** [comment]
Added makefile after hours of collaboration :)
