### ISSUE TITLE
TA Feedback (milestone 2):  Plots & figures

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/group29#69]
- Table 1 has too much information (and should also use human-readable values in the cells such as Test Accuracy rather than test_accuracy). Consider highlighting 2-3 of these measures only. Also, why exactly did you choose balanced log regression over the SVM with RBF? The reasoning behind this decision needs to be more explicit as there are conflicting numbers in the table.
- I suggest removing the scatterplot matrix if you do not plan to discuss it or use it in your analysis.

edit: second and third points adjusted/removed

**Comment by rachelywong** [comment]
@rachelywong first bullet, table 1, fix the writing
@jraza19 second bullet
@sukh2929 third bullet

**Comment by rachelywong** [comment]
Completed!
