### ISSUE TITLE
TA Feedback (milestone 2): Sampling

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/group29#70]
I was quite confused about why there were so few observations in the confusion matrix until I read that you took a subset of the data in the "future improvements" section. This should definitely be mentioned earlier when you outlined your procedure in the analysis section (also, if there was a reason for choosing exactly 1000, explain that as well!)

**Comment by rachelywong** [comment]
@rachelywong script 5

**Comment by rachelywong** [comment]
Completed!
