### ISSUE TITLE
TA Feedback (milestone 2): Clarity

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/group29#71]
- Overall you should try to be a bit more explicit regarding which features you ended up keeping and which you ended up dropping
- Be careful and more explicit with your conclusions: I would not say the balanced log regression performed "average" when its scores look comparable to the dummy classifier!

**Comment by rachelywong** [comment]
@rachelywong @jraza19 script 5

**Comment by rachelywong** [comment]
Completed!
