### ISSUE TITLE
Peer Review: 

### ISSUE THREAD

**Issue by IfyAnene7** [UBC-MDS/group29#73]
Communication:

- I really like how things are arranged in the `doc` folder. And using very clear files names such as `Project Proposal` makes it easy to navigate. I would suggest maybe changing the `script5` (I think this is the final report for this milestone) filename to something more self-explanatory. 

- The last sentence of the `exploratory data analysis` section in the `project proposal` (https://github.com/UBC-MDS/group29/blob/main/doc/ProjectProposal.md) talks about race not being an informative feature..... but forgot to include the reference, rather "(Include citation)" was used as a placeholder. 

Analysis and reasoning:

- Figure 1 in the `Results and Discussion` section of Script5.md isn't talked about enough. 

- I had no idea there were only 1000 observations used until I read the `Future Improvements` section. I think this should come earlier.

- I think you can also add why fit and score times, accuracy, and f1 scores were chosen as the evaluation metric. 

Suggestions:

- I know writing reports in groups can be tough cause everyone might be writing different sections and undertaking different analyses. So, something I find useful when the report is done (only if I have time!) is to copy and paste the writing aspects of the report into a word/spell checker like Grammarly to see if I made any errors or typos.

**Comment by jraza19** [comment]
Thanks @IfyAnene7 for your comments ahead of time!

**Comment by rachelywong** [comment]
Completed!
