### ISSUE TITLE
Edits to Makefile 

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/group29#74]
Please add any edits to the scripts that will affect the makefile here!

**Comment by jraza19** [comment]
I have decided to remove the figure from report but it will still get made by the EDA script. so no changes from script 2 so far.

**Comment by rachelywong** [comment]
- script4 --> changed the classifiers table but that should not have any major impacts on the makefile
- renamed script5 to diabetes_final_report.RMD

**Comment by jraza19** [comment]
script 3--> eda2.py - if the training/test split is added to the data cleaning file then the input argument for the eda2.py script will change to:

python src/eda2.py --input="data/raw/dataset_diabetes/diabetic_data_training.csv;data/processed/[ADD NAME OF TRAINING DATE HERE]" --output=reports/figures

**Comment by wiwang** [comment]
when we change the file name and output file name, we need to modify Makefile accordingly
