### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by deepaksidhu** [UBC-MDS/group29#80]
Hello team :wave:,

Overall, the project looks nicely done and it is evident that you guys put a lot of effort into it. I will briefly outline what I noticed while going through the group's project repository, since my comments are based on Milestone 3 submission, I feel like the group might have already addressed some of my recommendations.

* The report link in the readme looks broken. It leads to html file path that does not render.

* It was good to see that the group has incorporated a .gitignore file, and have added comments through it. This was extremely useful. But I feel like you can also add ipynb-checkpoints, and .DS_Store in it as well. I am not quite sure if there is reason fro why those files are showing in the root directory.

* Thanks as well for adding the dependencies together with the package version, since the team suggesting to use make all and clean for the reproducibility of the analysis pipeline it will be useful to add the dependency for GNU Make and it's package version.

* The Makefile is clear and with sufficient comments to help the users comprehend and follow though it.

* I checked the individual scripts, and I will compliment you guys for doing  a great job in handling exceptions and it is well documented. I will suggest that if you are able to change the script names to be more descriptive in terms of what there use is for, for example rename script5 to something that represents the content of script5.

* I really liked the future directions section, especially the third point.

* Overall you guys did great analyzing the data set, and It was cool to see you guys work on a health issue that is affecting the health care system.

Great job!

**Comment by rachelywong** [comment]
Thank you, Deepak! We will definitely fix the report link, the issue came from changing the script5 name. Thanks for your comments and suggestions :)

**Comment by sukh2929** [comment]
all changes done. closing the issue!
