### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by xudong-Y** [UBC-MDS/group29#82]
Hi there! Hope you are doing well. 

I took a look a look at your project and a few thoughts below:

- Documentation:
This project is well documented. I like the folder organization. Readme is straightforward and clear. There are plenty of comments in the scripts. Good work!

- Code
Code is clean and organized. 

- Analysis and reasoning
The final report has good analysis. Figure 1 is a little confusing for me, and I think a table with races and their corresponding readmission % would better serve the purpose. The reason to avoid racial bias might be a good enough reason to drop this feature :)
In addition, the column name 'X1' in table 1 could be changed to 'Model'.

- Communication
The report is clear and easy to follow. I enjoyed reading it. 

- Suggestions
The final report link in the Readme leads to a .Rmd file. It might be better to lead to a file format like .md so that it is easy to view on GitHub.

**Comment by rachelywong** [comment]
Thank you for your review! We ended up taking the scatterplot out of our report (Figure 1), and fixing our classifier table. Also, the final report link has been fixed as well!
