### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by JuntingHe** [UBC-MDS/group29#85]
Hi group29,

I hope all is well with you.

I reviewed your project and have some thoughts as follows:

-   Documentation: The project is well-documented, the organization of the folder is easy to navigate and the filename is clear and easy to understand. I think it may be better if the name of scripts in the src folder could have uniform format (some of their names having number at the end while some of them not)

-   Code: The code works well and  it is readable. Also, the results from it are reproducible. 

-   Analysis and reasoning: The analysis is reasonable and great for me. 

-   Communication: The report is clear and concise. I think the size of figure 2 is a little bit small and figure 3 does not align well at the bottom.

-   Suggestions: I think it will be better if I can know some brief information about model results in the summary part.

Overall, the project is great and I really enjoy reading it. Have a nice weekend!

**Comment by jraza19** [comment]
@JuntingHe Thank you for your feedback!
